### ISSUE TITLE
from longva.model.llava_arch import LlavaMetaModel, LlavaMetaForCausalLM ModuleNotFoundError: No module named 'longva'

### ISSUE THREAD

**Issue by SplendidYuan** [VectorSpaceLab/Video-XL#12]
_Video XL/videoxl/videoxl/model/language_madel/lava llama.py_ will report an error. I would like to ask how to import longva correctly

**Comment by shuyansy** [comment]
Do you want to use LLaMA as base-model?

**Comment by SplendidYuan** [comment]
> Do you want to use LLaMA as base-model?
I found this error while only running your pre trained shell script. I just downloaded longva from the website: [https://github.com/EvolvingLMMs-Lab/LongVA](https://github.com/EvolvingLMMs-Lab/LongVA). But I'm not sure if my operation is correct. Now the error message is:`ValueError: The checkpoint you are trying to load has model type `qwen2_vl` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.`But my Transformers was automatically installed according to the requirements.txt file

**Comment by Zzz0820** [comment]
I have the same problem as you, just change “ from longva.model.llava_arch import LlavaMetaModel, LlavaMetaForCausalLM” in the lava llama.py to “from ..llava_arch import LlavaMetaModel, LlavaMetaForCausalLM
”

**Comment by shuyansy** [comment]
Current code only support qwen-2 as base LLM. I will update it to support more versions of LLM like LLaMA

**Comment by SplendidYuan** [comment]
**Thank you very much for sharing the method**
