### ISSUE TITLE
I encountered numerous warnings while performing the info

### ISSUE THREAD

**Issue by ShbGao-ProMax** [VectorSpaceLab/Video-XL#21]
I encountered numerous warnings while performing the info, and the output seems relatively normal, but I'm not sure if it's achieving optimal performance. Could you give me some advice?
`/mnt/shbgao/miniconda3/envs/video_xl/lib/python3.10/site-packages/torch/nn/modules/module.py:2025: UserWarning: for vision_model.encoder.layers.12.self_attn.v_proj.weight: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(f'for {key}: copying from a non-meta parameter in the checkpoint to a meta '
/mnt/shbgao/miniconda3/envs/video_xl/lib/python3.10/site-packages/torch/nn/modules/module.py:2025: UserWarning: for vision_model.encoder.layers.12.self_attn.v_proj.bias: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)`

**Comment by shuyansy** [comment]
Is it appears in demo.py or inference? I think it is normal and will not affect the performance.

**Comment by ShbGao-ProMax** [comment]
Thank you!
it appears in demo.py, can u provide some suggestions to avoid them?  
by the way, k use CUDA 12.2 now, maybe i should reinstall a 11.8 version?

**Comment by ShbGao-ProMax** [comment]
Thank you very much for your prompt reply. I wish you all the best in your life！
