### ISSUE TITLE
Are there any examples to show?

### ISSUE THREAD

**Issue by Nuclear6** [VectorSpaceLab/Video-XL#6]
1. Video-XL can provide a summary of an hour-long movie, summarizing the main content of the movie by describing the main characters, settings and events of the movie.
2. Video-XL can identify abnormal segments in surveillance videos, such as abnormal behaviors or events detected in long-term surveillance videos.
3. Video-XL can identify advertisements inserted in long videos, which is very useful in advertising effectiveness evaluation and content review.

There are so many capabilities, but I don’t have an A800 GPU here. Can you make some examples for everyone to learn and understand?

**Comment by shuyansy** [comment]
Hi, we can not upload demos to github currently because of the storage limitation. So we upload some examples into https://drive.google.com/drive/folders/1CX0oXZ_ZuxG3J4WMvcmQMW8gc3NXI558?usp=share_link
